import "bootstrap-icons/font/bootstrap-icons.css";
import "bootstrap/dist/css/bootstrap.min.css";
import "glightbox/dist/css/glightbox.css";

import Script from "next/script";

import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import TopBar from "./components/TopBar";
import { Header } from "./components/Header";
import BackToTopBtn from "./components/BackToTopBtn";



const playFair = Playfair_Display({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-playFair-display",
  weight: ['400', '500', '600', '700', '800', '900'],
});

export const metadata: Metadata = {
  title: "Rey | Project101",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={playFair.className}>
        <TopBar />
        <Header />
        {children}
        <BackToTopBtn />
        </body>   
      {/* <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" 
      integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" 
      crossOrigin="anonymous" async></script> */}
    </html>
  );
}
